name: Building GSI..

on: [push]

env:
  ROM_URL: https://download.meizu.com/Firmware/Flyme/16s/8.20.8.18/cn_daily/20200818100123/28120e89/update.zip
  ROM_NAME: Flyme
  ZIP_NAME: Flyme-test
  TZ: Europe/London
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge

           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget expect p7zip-full p7zip-rar

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/00p513-dev/ErfanGSIs-channel ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh --ab $ROM_URL $ROM_NAME
         
       - name: Zip  
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs/output
              7z a $ZIP_NAME-CHANNEL.7z *-AB-*.img
              
       - name: Artifacts
         uses: actions/upload-artifact@v2
         with:
           name: Image
           path: ErfanGSIs/output/*-CHANNEL.7z
          
       - name: Print build info
         run: |
              cat ErfanGSIs/treet.txt
              cat ErfanGSIs/output/*-AB-*.txt
         
            
